services:
  redis:
    image: redis:latest
    container_name: helios-redis-dev
    ports:
      - "6379:6379"

  frontend:
    image: helios-frontend-dev
    container_name: helios-frontend-dev
    build:
      context: .
      dockerfile: frontend/dev.Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/frontend/node_modules

  backend:
    image: helios-backend-dev
    container_name: helios-backend-dev
    build:
      context: .
      dockerfile: backend/dev.Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/backend/node_modules
      
  nginx:
    image: nginx:latest
    container_name: helios-nginx-dev
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    