services:

  frontend:
    image: helios-frontend-dev
    container_name: helios-frontend-dev
    build:
      context: .
      dockerfile: frontend/dev.Dockerfile
    depends_on:
      - backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/frontend/node_modules

  backend:
    image: helios-backend-dev
    container_name: helios-backend-dev
    build:
      context: .
      dockerfile: backend/dev.Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/backend/node_modules

  nginx:
    image: nginx:latest
    container_name: helios-nginx-dev
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
